fields:
# sheet: call of cthulhu cult
  # row
    # col: col-12
      # card: cult: Cult Worksheet
        # row
          # col: col-12 col-md-3
  name:
    label: "Name"
    input: string
    required: true
          # /col
          # col: col-12 col-md-3
  deity:
    label: "Deity"
    input: string
          # /col
          # col: col-12 col-md-3
  year_setting:
    label: "Year/Setting"
    input: string
          # /col
          # col: col-12 col-md-3
  main location:
    label: "Main Location"
    input: string
          # /col
          # col: col-12 col-md-8
  goals means:
    label: "Goals/Means"
    input: text
    rows: 3
          # /col
          # col: col-12 col-md-4
  imageid:
    label: "Logo/Crest"
    input: integer
    render: image
          # /col
          # col: col-12
  structure:
    label: "Structure"
    input: text
    rows: 3
          # /col
          # col: col-12 col-md-6
  number of members:
    label: "Number of Members"
    input: string
          # /col
          # col: col-12 col-md-6
  archetypes:
    label: "Archetype/s"
    input: string
          # /col
          # col: col-12 col-md-4
  cm leader:
    label: "Cthulhu Mythos: Leader"
    input: string
          # /col
          # col: col-12 col-md-4
  cm members:
    label: "Cthulhu Mythos: Members"
    input: string
          # /col
          # col: col-12 col-md-4
  sl members:
    label: "Sanity Level of Members"
    input: string
          # /col
          # col: col-12 col-md-6
  initiation:
    label: "Initiation"
    input: text
    rows: 3
          # /col
          # col: col-12 col-md-6
  other locations:
    label: "Other Locations"
    input: text
    rows: 3
          # /col
          # col: col-12 col-md-6
  resources:
    label: "Resources"
    input: text
    rows: 3
          # /col
          # col: col-12 col-md-6
  tomes etc:
    label: "Tomes/Artifacts/Special"
    input: text
    rows: 3
          # /col
          # col: col-12 col-md-6
  security:
    label: "Security"
    input: text
    rows: 3
          # /col
          # col: col-12 col-md-6
  associated monsters:
    label: "Associated Monsters"
    input: text
    rows: 3
          # /col
          # col: col-12 col-md-6
  key dealings:
    label: "Key Dealings (Legal/Illegal)"
    input: text
    rows: 3
          # /col
          # col: col-12 col-md-6
  enemies weaknesses:
    label: "Enemies/Weaknesses"
    input: text
    rows: 3
          # /col
        # /row
        # row
          # col: col-12
  description:
    label: "Notes"
    input: text
    rows: 3
          # /col
        # /row
      # /card
    # /col
  # /row
# /sheet