fields:
# include: include/header.twig
# include: include/data.twig
# sheet: Enshrounded Character Sheet
  # row
    # col: col-12 col-md-8
      # card: personal: Personal Information
        # card-body
          # row
            # col: col-4 col-md-4
  Name:
    label: "Character Name"
    input: string
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Race:
    label: "Race"
    input: string
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Alignment:
    label: "Alignment"
    input: string
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Height:
    label: "Height"
    input: string
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Weight:
    label: "Weight"
    input: string
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Age:
    label: "Age"
    input: integer
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Gender:
    label: "Gender"
    input: string
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Faith:
    label: "Faith"
    input: string
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Primary Class:
    label: "Primary Class"
    input: string
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Specialization:
    label: "Specialization"
    input: string
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Profession:
    label: "Profession"
    input: string
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Level:
    label: "Level"
    input: integer
    min: 0
    max: 40
    placeholder: ""
            # /col
            # col: col-4 col-md-4
  Rank:
    label: "Rank"
    input: integer
    min: 0
    max: 12
    placeholder: ""
            # /col
          # /row
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-4
      # card: portrait: Character Portrait
        # card-body
  img:
    input: integer
    render: image
    placeholder: "WA Image ID"
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-4
      # card: status: Status
        # card-body
  Health Current:
    label: "Health Current"
    input: integer
    placeholder: ""
  Wound Status:
    label: "Wound Status"
    input: string
    min: 0
    max: 5
  Energy Current:
    label: "Energy Current"
    input: integer
    placeholder: ""
  Enervation Level:
    label: "Enervation Level"
    input: integer
    min: 0
    max: 5
    placeholder: ""
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-8
      # card: attributes: Ability Scores
        # card-body
          # iter: att_list
  Att Base:
    label: "Ability Base"
    input: integer
    min: 0
    max: 40
          # /iter
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: vulnerable-points: Vulnerable Points
        # card-body
  VP Head:
    label: "Head"
    input: integer
  VP LArm:
    label: "Left Arm"
    input: integer
  VP RArm:
    label: "Right Arm"
    input: integer
  VP Torso:
    label: "Torso"
    input: integer
  VP LHand:
    label: "Left Hand"
    input: integer
  VP RHand:
    label: "Right Hand"
    input: integer
  VP LLeg:
    label: "Left Leg"
    input: integer
  VP RLeg:
    label: "Right Leg"
    input: integer
  VP LFoot:
    label: "Left Foot"
    input: integer
  VP RFoot:
    label: "Right Foot"
    input: integer
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: ini-and-speed: Initiative and Speed
        # card-body
  Night Vision:
    label: "Night Vision"
    input: integer
    min: 0
    max: 999
  Walking Speed:
    label: "Walking Speed"
    input: integer
    min: 0
    max: 999
  Climbing Speed:
    label: "Climbing Speed"
    input: integer
    min: 0
    max: 999
  Swimming Speed:
    label: "Swimming Speed"
    input: integer
    min: 0
    max: 999
  Flying Speed:
    label: "Flying Speed"
    input: integer
    min: 0
    max: 999
        # /card-body
      # /card
      # card: competency-and-language: Competency and Language
        # card-body
  cal Armor:
    label: "Armor"
    input: string
    placeholder: ""
  cal Weapons:
    label: "Weapons"
    input: string
    placeholder: ""
  cal Tools:
    label: "Tools"
    input: string
    placeholder: ""
  cal Languages:
    label: "Languages"
    input: string
    placeholder: ""
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12
      # card: resistances: Resistances
        # card-body
        # iter: resistance_list
  Resistance:
    label: ""
    input: select
    options:
      "Vulnerable" : "Vulnerable"
      "Resistant" : "Resistant"
      "Immune" : "Immune"
          # /iter
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12
      # card: skills: Skills
        # card-body
          # iter: skill_list: 0
  Skill Value:
    label: "Value"
    input: integer
    max: 99
  Skill Level:
    label: "Level"
    input: select
    options:
      "Normal" : "Normal"
      "Practiced" : "Practiced"
      "Specialized" : "Specialized"
          # /iter
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12
      # card: abilities: Abilites
      # /card
    # /col
    # col: col-12 col-md-6
      # card: abilities: At Will
        # card-body
          # iter: 5
  Ability Name At Will:
    input: string
    placeholder: ""
          # /iter
        # /card-body
      # /card
      # card: abilities: Reflex
        # card-body
          # iter: 5
  Ability Name Reflex:
    input: string
    placeholder: ""
          # /iter
        # /card-body
      # /card
      # card: abilities: Action
        # card-body
          # iter: 16
  Ability Name Action:
    input: string
    placeholder: ""
          # /iter
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: abilities: Perk
        # card-body
          # iter: 5
  Ability Name Perk:
    input: string
    placeholder: ""
          # /iter
        # /card-body
      # /card
      # card: abilities: Utility
        # card-body
          # iter: 5
  Ability Name Utility:
    input: string
    placeholder: ""
          # /iter
        # /card-body
      # /card
      # card: abilities: Remedy
        # card-body
          # iter: 5
  Ability Name Remedy:
    input: string
    placeholder: ""
          # /iter
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12
      # card: equipped-items: Equipped Items
        # card-body
          # iter: equipped_list
  EI Name:
    label: ""
    input: string
  EI Value:
    label: ""
    input: string
          # /iter
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-12
      # card: inventory: Inventory
        # card-body
  Purse Equipped:
    label: "Equipped"
    input: checkbox
  Deposit Box Location:
    label: "Deposit Box Location"
    input: string
  Jatocan Crown:
    label: "Jatocan Crown"
    input: integer
  Obsidial:
    label: "Obsidial"
    input: integer
  Gucal:
    label: "Gucal"
    input: integer
  Frostmark:
    label: "Frostmark"
    input: integer  
  Thornleaf:
    label: "Thornleaf"
    input: integer
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: inventory: Pockets
        # card-body
  Pockets Equipped:
    label: "Equipped"
    input: checkbox
          # table: horiz
            # iter: 15
              # width: 20%
  Pockets Qty:
    label: "Qty"
    input: integer
  Pockets Name:
    label: "Item Name"
    input: string
              # width: 20%
  Pockets Lbs:
    label: "Lbs"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: inventory: Tool Box
        # card-body
  Toolbox Equipped:
    label: "Equipped"
    input: checkbox
          # table: horiz
            # iter: 15
              # width: 20%
  Toolbox Qty:
    label: "Qty"
    input: integer
  Toolbox Name:
    label: "Item Name"
    input: string
              # width: 20%
  Toolbox Lbs:
    label: "Lbs"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: inventory: Scroll Case
        # card-body
  Scroll Case Equipped:
    label: "Equipped"
    input: checkbox
          # table: horiz
            # iter: 15
              # width: 20%
  Scroll Case Qty:
    label: "Qty"
    input: integer
  Scroll Case Name:
    label: "Item Name"
    input: string
              # width: 20%
  Scroll Case Lbs:
    label: "Lbs"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: inventory: Component Pouch
        # card-body
  Component Pouch Equipped:
    label: "Equipped"
    input: checkbox
          # table: horiz
            # iter: 30
              # width: 20%
  Component Pouch Qty:
    label: "Qty"
    input: integer
  Component Pouch Name:
    label: "Item Name"
    input: string
              # width: 20%
  Component Pouch Lbs:
    label: "Lbs"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: inventory: Rucksack
        # card-body
  Rucksack Equipped:
    label: "Equipped"
    input: checkbox
          # table: horiz
            # iter: 80
              # width: 20%
  Rucksack Qty:
    label: "Qty"
    input: integer
  Rucksack Name:
    label: "Item Name"
    input: string
              # width: 20%
  Rucksack Lbs:
    label: "Lbs"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
    # col: col-12 col-md-6
      # card: inventory: Deposit Box
        # card-body
          # table: horiz
            # iter: 15
              # width: 20%
  Deposit Box Qty:
    label: "Qty"
    input: integer
  Deposit Box Name:
    label: "Item Name"
    input: string
              # width: 20%
  Deposit Box Lbs:
    label: "Lbs"
    input: string
            # /iter
          # /table
        # /card-body
      # /card
    # /col
  # /row
  # row
    # col: col-12 col-md-12
      # card: notes: Notes
        # card-body: mention
  Notes:
    input: text
    rows: 4
        # /card-body
      # /card
    # /col
  # /row
  # br
  # hr
  # br
  # include: include/footer.twig
# /sheet